### ISSUE TITLE
Grafana dashboard downloads

### ISSUE THREAD

**Issue by danielc103** [maddevsio/aws-eks-base#32]
Init container failure on prometheus helm chart for grafana.

```yaml
Init Containers:
  download-dashboards:
    Container ID:  docker://7c114db55c4586c75a32740a628b7e8c343f43d4de0ed1f10d208046c2b1e3ca
    Image:         curlimages/curl:7.73.0
    Image ID:      docker-pullable://curlimages/curl@sha256:5329ee280d3d91f3e48885f18c884af5907b68c6aa80f411927a5a28c4f5df07
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
      mkdir -p /var/lib/grafana/dashboards/default && /bin/sh /etc/grafana/download_dashboards.sh
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    6
```

`downlaod_dashboard.sh`

```shell
curl -vskf \                                                                                                                            
--connect-timeout 60 \
--max-time 60 \
-H "Accept: application/json" \
-H "Content-Type: application/json;charset=UTF-8" \
  "https://grafana-dashboards.maddevs.org/common/aws-eks-base/postgresql-database.json"
* Could not resolve host: grafana-dashboards.maddevs.org
* Closing connection 0
```
