### ISSUE TITLE
Filebeat not picking up all logs 

### ISSUE THREAD

**Issue by danielc103** [maddevsio/aws-eks-base#41]
This may be more of a question than an actual issue.

I've not made any modifications to the filebeat deployment. 

Kibana successfully pulls logs for my autoscaler and elk stack. Kibana picks up all my namespaces correctly, but for some reason does not show logs for nginx-ingress, external-dns, or any other services. I've deployed an AWX operator into default namespace, no logs.

Am I missing a setting or flag I should toggle in Kibana or Elasticsearch to pull those?

```yml
filebeat:
  enabled: true
  filebeatConfig:
    filebeat.yml: |
      filebeat.modules:
        - module: system
          syslog:
            enabled: true
            #var.paths: ["/var/log/syslog"]
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            node: $${NODE_NAME}
            hints.enabled: true
            hints.default_config:
              type: container
              paths:
                - /var/log/containers/*-$${data.kubernetes.container.id}.log

      processors:
        - drop_event:
            when:
              equals:
                kubernetes.container.name: "filebeat"

        - add_cloud_metadata:
        - add_kubernetes_metadata:
        - add_docker_metadata:

      output.elasticsearch:
        username: '$${ELASTICSEARCH_USERNAME}'
        password: '$${ELASTICSEARCH_PASSWORD}'
        protocol: https
        hosts: ["elasticsearch-master:9200"]
        ssl.verification_mode: none
```

**Comment by danielc103** [comment]
I was able to resolve my issue by modifying the input for Filebeat

```yml
filebeat:
  enabled: true
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
          - add_kubernetes_metadata:
              host: $${NODE_NAME}
              matchers:
              - logs_path:
                  logs_path: "/var/log/containers/"
      filebeat.modules:
        - module: system
          syslog:
            enabled: true
            #var.paths: ["/var/log/syslog"]
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            node: $${NODE_NAME}
            hints.enabled: true
            hints.default_config:
              type: container
              paths:
                - /var/log/containers/*-$${data.kubernetes.container.id}.log

      processors:
        - drop_event:
            when:
              equals:
                kubernetes.container.name: "filebeat"

        - add_cloud_metadata:
        - add_kubernetes_metadata:
        - add_docker_metadata:

      output.elasticsearch:
        username: '$${ELASTICSEARCH_USERNAME}'
        password: '$${ELASTICSEARCH_PASSWORD}'
        protocol: https
        hosts: ["elasticsearch-master:9200"]
        ssl.verification_mode: none
```

This config successfully pulls all the container logs into Kibana (Elasticsearch). Not sure if this is what you intended.  On that same note, I was wondering what purpose does running Loki and Filebeat together serve?
